---
title: "Multi100_Huijts_EurSocioRev_2013_OY3B"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

# Hypotesis to analyze

_The disadvantage in psychological well-being of childless people is smaller in countries with tolerant norms towards childlessness (p. 32)_

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)
library(lmerTest)
library(broom)
library(broom.mixed)
library(ggbeeswarm)
library(performance)
library(sjPlot)

theme_set(theme_light())

```

```{r}
edu_levels <- c("Primary", "Lower secondary", "Upper secondary", "Teritary", "Missing")

wb <- 
  read_csv(here("data/SRD Huijts data final.xls")) %>% 
  mutate(gender = recode(gndr, `1` = "Male", `2` = "Female"),
         # Create centered age (to avoid multicollinearity) and age^2
         age_ctd = scale(agea, scale = FALSE) %>% as.numeric(),
         age_ctd2 = age_ctd^2,
         # Set education baseline to Primary, set explicit NA
         edu = fct_explicit_na(edu, na_level = "Missing") %>% 
               fct_relevel(edu_levels),
         paredu = fct_relevel(paredu, edu_levels),
         # Set parental status baseline to living with children
         par_stat = fct_relevel(par_stat, "Living w children"),
         # Correcting a rounding error for country: SI
         childless_disapp_std = if_else(cntry == "SI", 0.1954625, childless_disapp_std)
         )
```



```{r}
wb_lmer <- 
  wb %>% 
  # select(wellbeing,
  #        Age = age_ctd, 
  #        `Age square` = age_ctd2,
  #        `Marital status` = married,
  #        `Educational level` = edu,
  #        `Educational level of parents` = paredu,
  #        `Religious attendance` = rel,
  #        `Paid employment` = pdwrk,
  #        `Born in country` = brncntr,
  #        `Parental status` = par_stat,
  #        Country = cntry,
  #        `Disapproval of childlessness` = childless_disapp_std,
  #        `Social contacts` = sclmeet) %>% 
  group_by(gender) %>% 
  nest() %>% 
  mutate(model = map(data, 
                     ~lmer(
                       wellbeing ~ age_ctd + age_ctd2 + married + edu + paredu + 
                                   rel + pdwrk + brncntr + sclmeet + 
                                   par_stat * childless_disapp_std + 
                                   (1 | cntry),
                       data = .x)), 
         model_tidy = map(model, tidy, conf.int = TRUE))

wb_lmer %>% 
  pull(model) %>% 
  set_names(pull(wb_lmer, gender)) %>% 
  tab_model(
          dv.labels = c("Male", "Female"),
          show.std = TRUE,
          show.est = FALSE,
          show.se = TRUE,
          show.reflvl = TRUE, 
          show.ci = FALSE,
          show.aic = TRUE,
          show.dev = TRUE,
          prefix.labels = "varname")

isSingular(wb_lmer$model[[1]])
isSingular(wb_lmer$model[[2]])

# wb_lmer$model[[1]]@vcov_beta %>% row.names() %>% sort()

```


```{r}
#Visualize results
# Separate linear regressions by country by gender
wb_lm <- 
  wb %>% 
  group_by(country = cntry, gender, childless_disapp_std) %>% 
  nest() %>% 
  mutate(model = map(data, 
                      ~lm(wellbeing ~ par_stat + age_ctd + age_ctd2 + married + 
                                      edu + paredu + rel + pdwrk + brncntr +
                                      sclmeet,
                                      data = .x)),
         model_tidy = map(model, tidy, conf.int = TRUE),
         n = map_int(data, nrow))

wb_lm %>% 
    unnest(model_tidy) %>% 
    ungroup() %>% 
    filter(str_detect(term, "par_stat")) %>% 
    select(childless_disapp_std:country, term, estimate, n) %>% 
    ggplot() +
    aes(x = childless_disapp_std, y = estimate, color = term, group = term) +
    geom_point(aes(size = n), alpha = .5) +
    geom_smooth(method = "lm", mapping = aes(weight = n), se = FALSE) + 
    geom_text(aes(label = country), check_overlap = TRUE, color = "black") +
    facet_wrap(~gender) +
    labs(title = "Association between effect size (beta) of pariatal status and well-being and childlessness disapproval",
         subtitle = "Effects are in comparison with living with children. Lines show weighted regressions.",
         x = "Childlessness disapproval",
         y = "Effect of parental status on well-being",
         color = "Parental status")
```

Childlessness disapproval is negatively associated well-being in childless females, compared to those living with children. 

We did not find this association in males. However 


# SANDBOX
```{r}


wb %>% 
  group_by(count)
  ggplot() +
  aes(x = childless_disapp_std, y = wellbeing, color = par_stat) +
  geom_point(alpha = .3) +
  geom_smooth(method = "lm") + 
  facet_wrap(~gender)
  
  
wb %>% 
  mutate(childless_disapp_std = if_else(cntry == "SI", 0.1954625, childless_disapp_std)) %>% 
  select(country = cntry, gender, childless_disapp_std) %>% 
  filter(country == "SI") %>% #view()
  pull(childless_disapp_std) %>% 
  `/`(0.1954625)
  view()



```

